package UHART.Views;


import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

import com.mongodb.client.MongoCollection;

import org.bson.Document;

import java.awt.event.ActionEvent;

import UHART.Controllers.DBConnection;
import UHART.Controllers.LoginManager;
import UHART.Models.*;
import UHART.Models.Staff_Model.USER_ROLE;

/**
 *
 * @author Yixun
 */
public class PatientPageFrm extends javax.swing.JPanel {

    javax.swing.GroupLayout layout;
   
    private Patient patient;
    private Staff_Model user;
    private Document patientID = new Document();        
    private String medications;
    private String symptoms;
    private String diagnosis;

    private DBConnection db = new DBConnection();
    private static final long serialVersionUID = 1L;    
    private MongoCollection<Document> patientCollection = db.getDB().getCollection("patients");  
    
    public PatientPageFrm(final Patient patient, final Staff_Model user, final LoginManager loginManager) {
        //System.out.println(patient.toString());
        initComponents(patient, user, loginManager);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(final Patient patient, final Staff_Model user, final LoginManager loginManager) {
        patientID.put("id", patient.getID());
        loginManager.setContentPane(this);
        this.patient = patient;
        this.user = user;


        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();

        JButton addMed = new JButton("Add");
        JButton addDiagnosis = new JButton("Add");
        JButton addSymptom = new JButton("Add");


        setNextFocusableComponent(jScrollPane1);
        setLayout(new java.awt.BorderLayout());

        //jTextArea3.setEditable(false);
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {                
            },
            new String [] {
                "Date", "Reason"
            }
        ) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane5.setViewportView(jTable1);

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.REGISTER)
        {
            DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            for(MedicalHistory medHist : patient.getMedicalHistory())
            {
                model.addRow(new Object[] {medHist.getDate(), medHist.getReason()});
            }
        }

        /*
        Author: Tyler
        Description: Access Control
        */        
        USER_ROLE role = user.getUSER_ROLE();
        switch(role)
        {
            case BILLING:
                jTextField1.setVisible(false);
                //jTextField2.setVisible(false);
                jTextField3.setVisible(false);
                jTextField4.setVisible(false);
                jTextField5.setVisible(false);
                jTextField6.setVisible(false);
                jTextField7.setVisible(false);
                jTextField8.setVisible(false);
                jTextField9.setVisible(false);
                //jTextField10.setVisible(false);
                //jTextField11.setVisible(false);
                //jTextField12.setVisible(false);
                //jTextField13.setVisible(false);
                //jTextField14.setVisible(false);
                jTextField15.setVisible(false);
                jTextField16.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel1.setVisible(false);
                //jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
               // jLabel10.setVisible(false);
                //jLabel11.setVisible(false);
                //jLabel12.setVisible(false);
                //jLabel13.setVisible(false);
                //jLabel14.setVisible(false);
                //jLabel15.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel18.setVisible(false);
                jLabel19.setVisible(false);
                jLabel20.setVisible(false);
                jLabel21.setVisible(false);
                jLabel22.setVisible(false);
                jTextArea1.setVisible(false);
               // jTextArea3.setVisible(false);
                jButton4.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jPanel2.setVisible(false);
                jScrollPane3.setVisible(false);
                jScrollPane2.setVisible(false);
                addMed.setVisible(false);
                addDiagnosis.setVisible(false);
                break;
            case NURSE:
                jTextArea1.setVisible(false);
                jTextField19.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jCheckBox1.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel15.setVisible(false);
                jLabel18.setVisible(false);
                jLabel22.setVisible(false);
                jButton4.setVisible(false);
                addMed.setVisible(false);
                addDiagnosis.setVisible(false); 
                //jTextArea3.setEditable(true);               
                break;
            case REGISTER:
                jTextArea1.setVisible(false);
               // jTextArea3.setVisible(false);
                jTextField19.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jCheckBox1.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel15.setVisible(false);
                addMed.setVisible(false);
                addDiagnosis.setVisible(false);
                break;
            case DOCTOR:
                jTextField19.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jLabel22.setVisible(false);
                jLabel18.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel19.setVisible(false);
                jButton4.setVisible(false);
                jCheckBox1.setVisible(false);
        }

        jLabel1.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel1.setText("Gender:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel2.setText("Provider: ");

        jLabel3.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel3.setText("Phone Number: ");

        jLabel4.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel4.setText("SSN:");

        jLabel5.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel5.setText("Physician:");

        jLabel6.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel6.setText("Physician Number:");

        jLabel7.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel7.setText("Allergies seperated by commas:");

        jLabel8.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel8.setText("Symptons seperated by commas:");

        jLabel9.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel9.setText("Medications seperated by commas:");

        jLabel10.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel10.setText("Street Number:");

        jLabel11.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel11.setText("City:");

        jLabel12.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel12.setText("State:");

        jTextField1.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField1.setText(patient.getGender());
        jTextField1.setEditable(false);

        jTextField2.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField2.setText(patient.getProvider());
        jTextField2.setEditable(false);

        jTextField3.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField3.setText(patient.getPhone());
        jTextField3.setEditable(false);

        jTextField4.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField4.setText("" + patient.getSSN());
        jTextField4.setEditable(false);

        jTextField5.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField5.setText(patient.getPhysician());
        jTextField5.setEditable(false);

        jTextField6.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField6.setText(patient.getPhysicianNumber());
        jTextField6.setEditable(false);

        String allergies = "";
        for(String allergy: patient.getAllergies())
        {
            if(allergies.isEmpty())
            {
                allergies = allergy;
            }
            else
            {
                allergies += ", " +allergy;
            }
        }

        jTextField7.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField7.setText(allergies);
        jTextField7.setEditable(false);

        symptoms = "";
        for(Symptoms symptom: patient.getSymptoms())
        {
            if(symptoms.isEmpty())
            {
                symptoms = symptom.toString();
            }
            else
            {
                symptoms += ", " +symptom.toString();
            }
        }

        jTextField8.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField8.setText(symptoms);
        jTextField8.setEditable(false);

        medications = "";
        for(String medication: patient.getMedications())
        {
            if(medications.isEmpty())
            {
                medications = medication.toString();
            }
            else
            {
                medications += ", " +medication.toString();
            }
        }

        jTextField9.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField9.setText(medications);
        jTextField9.setEditable(false);        

        jTextField10.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField10.setText(patient.getAddress().getStreet());
        jTextField10.setEditable(false);

        jTextField11.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField11.setText(patient.getAddress().getCity());
        jTextField11.setEditable(false);

        jTextField12.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField12.setText(patient.getAddress().getState());
        jTextField12.setEditable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel15.setText("Symptoms:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel16.setText("Diagnosis:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Diagnoses.ABDOMINALPAIN.toString(),
            UHART.Models.Diagnoses.ACUTEUPPERRESPIRATORYINFECTION.toString(),
            UHART.Models.Diagnoses.CHESTPAIN.toString(),
            UHART.Models.Diagnoses.DIZZINESSANDGIDDINESS.toString(),
            UHART.Models.Diagnoses.HEADACHE.toString(),
            UHART.Models.Diagnoses.INJURYOFHEAD.toString(),
            UHART.Models.Diagnoses.LOWERBACKPAIN.toString(),
            UHART.Models.Diagnoses.NONINFECTIVEGASTROENTERITISANDCOLITIS.toString(),
            UHART.Models.Diagnoses.SYNCOPEANDCOLLAPSE.toString(),
            UHART.Models.Diagnoses.URINARYTRACTINFECTION.toString()}));

        jLabel17.setText("Medicines: ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Medications.ACETAMINOPHEN.toString(),
            UHART.Models.Medications.ANTACID.toString(), 
            UHART.Models.Medications.ANTIBIOTIC.toString(),
            UHART.Models.Medications.ANTISEIZURE.toString(),
            UHART.Models.Medications.ASPIRIN.toString(),
            UHART.Models.Medications.FOSCARNET.toString(),
            UHART.Models.Medications.GANCICLOVIR.toString(),
            UHART.Models.Medications.IBUPROFIN.toString(),
            UHART.Models.Medications.SIMETHICONE.toString(),
            UHART.Models.Medications.SUGAR.toString(),
            UHART.Models.Medications.VALGANCICLOVIR.toString()}));

        jLabel19.setText("Nurse info: ");

        jButton4.setText("Add Medical History");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        addMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                String medication = jComboBox3.getSelectedItem().toString();
                if(!patient.getMedications().contains(medication))
                {
                    db.createMedications(medication, user, patientID);
                    patient.addMedication(medication);

                    if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ACETAMINOPHEN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ACETAMINOPHEN);
                        db.addBill(UHART.Models.Medications.ACETAMINOPHEN, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTACID.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTACID);
                        db.addBill(UHART.Models.Medications.ANTACID, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTIBIOTIC.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTIBIOTIC);
                        db.addBill(UHART.Models.Medications.ANTIBIOTIC, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTISEIZURE.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTISEIZURE);
                        db.addBill(UHART.Models.Medications.ANTISEIZURE, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.SUGAR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.SUGAR);
                        db.addBill(UHART.Models.Medications.SUGAR, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.IBUPROFIN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.IBUPROFIN);
                        db.addBill(UHART.Models.Medications.IBUPROFIN, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.SIMETHICONE.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.SIMETHICONE);
                        db.addBill(UHART.Models.Medications.SIMETHICONE, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.GANCICLOVIR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.GANCICLOVIR);
                        db.addBill(UHART.Models.Medications.GANCICLOVIR, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.FOSCARNET.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.FOSCARNET);
                        db.addBill(UHART.Models.Medications.FOSCARNET, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ASPIRIN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ASPIRIN);
                        db.addBill(UHART.Models.Medications.ASPIRIN, patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.VALGANCICLOVIR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.VALGANCICLOVIR);
                        db.addBill(UHART.Models.Medications.VALGANCICLOVIR, patientCollection, patientID);
                    }                    
                    

                    if(medications.isEmpty())
                    {
                        medications = jComboBox3.getSelectedItem().toString();
                    }
                    else
                    {
                        medications += ", "  +jComboBox3.getSelectedItem().toString();
                    }
                }
                else
                {
                    //TODO: Popup message
                    System.out.println("Medication already added");
                }
            }
        });

        addDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                String diagnosis = jComboBox2.getSelectedItem().toString();
                if(!patient.getDiagnosis().contains(diagnosis))
                {
                                        
                    db.createDiagnosis(diagnosis, user, patientID);
                    patient.addDiagnosis(diagnosis);

                    if(diagnosis.isEmpty())
                    {
                        diagnosis = jComboBox2.getSelectedItem().toString();
                    }
                    else
                    {
                        diagnosis += ", "  +jComboBox2.getSelectedItem().toString();
                    }
                }
                else
                {
                    //TODO: Popup message
                    System.out.println("Diagnosis already added");
                }
                
                

            }
        });

        //TODO: Implement with button
        addSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(!jTextArea1.getText().isEmpty())
                {
                    String[] symptomValues = jTextArea1.getText().split(",");    

                    for(int i = 0; i < symptomValues.length; i++)
                    {
                        if(!patient.getSymptoms().get(i).toString().equals(symptomValues[i]))
                        {
                            Symptoms symptom = new Symptoms(symptomValues[i].replaceAll("\\s+", ""));
                            db.createSymptoms(symptom, patientCollection, patientID);
                            patient.setSymptoms(symptom);

                            if(symptoms.isEmpty())
                            {
                                symptoms = symptomValues[i].replaceAll("\\s+", "");
                            }
                            else
                            {
                                symptoms += ", " + symptomValues[i].replaceAll("\\s+", "");
                            }
                        }
                        else
                        {
                            //TODO: Popup button
                            System.out.println(symptomValues[i] + " already added");
                        }                        
                        
                    }
                    
                }

            }
        });

        jLabel18.setText("Date:");

        jLabel22.setText("Medication:");

        jTextField17.setText("jTextField17");

        jTextField18.setText("jTextField18");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nurse", "Date", "Progess"
            }
        ) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable2);

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.REGISTER)
        {
            DefaultTableModel model =(DefaultTableModel) jTable2.getModel();
            for(ProgressReport prog : patient.getProgressReports())
            {
                model.addRow(new Object[] {prog.getNurseName(), prog.getDate(), prog.getNote()});
            }
        }

        jLabel25.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel25.setText("Diagnosis");

        jLabel26.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel26.setText("Ordering tests");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Tests_procedures.ANGIOGRAM.toString(),
            UHART.Models.Tests_procedures.BLOODTEST.toString(),
            UHART.Models.Tests_procedures.CTSCAN.toString(),
            UHART.Models.Tests_procedures.ECHOCARDIOGRAM.toString(),
            UHART.Models.Tests_procedures.LATERALNECKXRAY.toString(),
            UHART.Models.Tests_procedures.REHABILITATION.toString(),
            UHART.Models.Tests_procedures.STRESSTEST.toString(),
            UHART.Models.Tests_procedures.SURGERY.toString(),
            UHART.Models.Tests_procedures.URINETEST.toString()
        }));

        jLabel27.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel27.setText("Patient Admitted");


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField17)
                                        .addComponent(jTextField18))))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField20)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 50, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jCheckBox2))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jLabel13.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel13.setText("Zip:");

        jLabel14.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel14.setText("Country:");

        jTextField13.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField13.setText(patient.getAddress().getZipcode());
        jTextField13.setEditable(false);

        jButton1.setText("Back");
        jButton1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                loginManager.showMainPanel(user);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.setVisible(false);
        jButton3.addActionListener(new ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        jTextField14.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField14.setText(patient.getAddress().getcountry());
        jTextField14.setEditable(false);

        jTextField15.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField15.setText(patient.getName());
        jTextField15.setEditable(false);

        jLabel20.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel20.setText("Date of Birth:");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel21.setText("Name: ");
        jLabel21.setToolTipText("");

        //TODO: Fix date format
        jTextField16.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField16.setText(patient.getDateOfBirthString());
        jTextField16.setEditable(false);

        jLabel23.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel23.setText("Bill: ");

        jTextField19.setFont(new java.awt.Font("����", 0, 20)); // NOI18N\
        jTextField19.setEditable(false);
        if(user.getUSER_ROLE() == UHART.Models.Staff_Model.USER_ROLE.BILLING)
        {
            if(patient.getBill().getPrice() == 0)
            {
                jTextField19.setText("$0");
                jCheckBox1.setSelected(true);
            }
            else
            {
                jTextField19.setText("$" +patient.getBill().getPrice());
            }
    
        }       
        
        jCheckBox1.setText("Bill Paid");
        jCheckBox1.setVisible(false);
    

        jLabel24.setText("Bill state");
        jLabel24.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jCheckBox1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton3)
                        .addContainerGap(456, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(93, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField10, jTextField11, jTextField12, jTextField13, jTextField14, jTextField15, jTextField16, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField10, jTextField11, jTextField12, jTextField13, jTextField14, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9});

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    //EDIT
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton3.setVisible(true);
        jButton2.setVisible(false);        

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.BILLING)
        {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
            jTextField9.setEditable(true);
            jTextField10.setEditable(true);
            jTextField11.setEditable(true);
            jTextField12.setEditable(true);
            jTextField13.setEditable(true);
            
            jTextField15.setEditable(true);
            jTextField14.setEditable(true);
            jTextField16.setEditable(true);        
        }
        else
        {
            jCheckBox1.setVisible(true);
            jLabel24.setVisible(true);
        }       
        

    }//GEN-LAST:event_jButton2ActionPerformed

    //SAVE
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
       
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);
        jTextField14.setEditable(false);
        jTextField15.setEditable(false);
        jTextField16.setEditable(false);
        jTextField19.setEditable(false);
        jButton3.setVisible(false);
        jButton2.setVisible(true);

        jCheckBox1.setVisible(false);
        jLabel24.setVisible(false);

        if(jCheckBox1.isSelected())
        {
            //TODO: Implement billing features
            patient.markPaid();
            jTextField19.setText("$" +patient.getBill().getPrice());
            db.markBillPaid(patientID);
        }    
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[] { jTextField17.getText(), jTextField18.getText()});

        MedicalHistory medHistory = new MedicalHistory(jTextField17.getText(), jTextField18.getText());
        
        //System.out.println(patient.getID());

        db.createMedicalHistory(medHistory, patientID);

        jTextField18.setText("");
        jTextField17.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

   
    

}