package UHART.Views;


import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

import com.mongodb.client.MongoCollection;

import org.bson.Document;

import java.awt.event.ActionEvent;

import UHART.Controllers.DBConnection;
import UHART.Controllers.LoginManager;
import UHART.Models.*;
import UHART.Models.Staff.Nurse;
import UHART.Models.Staff_Model.USER_ROLE;

/**
 *
 * @author Yixun
 */
public class PatientPageFrm extends javax.swing.JPanel {

    javax.swing.GroupLayout layout;
   
    private Patient patient;
    private Staff_Model user;
    private Document patientID = new Document();        
    private String medications;
    private String symptoms;
    private String diagnosis;

    private DBConnection db = new DBConnection();
    private static final long serialVersionUID = 1L;    
    private MongoCollection<Document> patientCollection = db.getDB().getCollection("patients");  
    
    public PatientPageFrm(final Patient patient, final Staff_Model user, final LoginManager loginManager) {
        //System.out.println(patient.toString());
        initComponents(patient, user, loginManager);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(final Patient patient, final Staff_Model user, final LoginManager loginManager) {
        java.awt.GridBagConstraints gridBagConstraints;
        patientID.put("id", patient.getID());

       // loginManager.setVisible(false);
        loginManager.setContentPane(this);
        this.patient = patient;
        this.user = user;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setNextFocusableComponent(jScrollPane1);
        setLayout(new java.awt.GridBagLayout());

        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        jTable2.setVisible(false);
        jTextField22.setVisible(false);
        jTextField23.setVisible(false);
        jTextField24.setVisible(false);
        jCheckBox2.setVisible(false);        
        jButton8.setVisible(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);
        jTextArea1.setVisible(false);
        jTextArea2.setVisible(false);
        jButton10.setVisible(false);
        /*
        Author: Tyler
        Description: Access Control
        */        
        USER_ROLE role = user.getUSER_ROLE();
        switch(role)
        {
            case BILLING:
                jTextField1.setVisible(false);
                jTextField3.setVisible(false);
                jTextField4.setVisible(false);
                jTextField5.setVisible(false);
                jTextField6.setVisible(false);
                jTextField7.setVisible(false);
                jTextField8.setVisible(false);
                jTextField16.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel18.setVisible(false);
                jLabel19.setVisible(false);
                jLabel20.setVisible(false);
                jLabel22.setVisible(false);
                jButton4.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jPanel2.setVisible(false);
                jScrollPane3.setVisible(false);
                jScrollPane2.setVisible(false);
                break;
            case NURSE:              
                jTextArea2.setVisible(true);
                jButton10.setVisible(true);  
                jTextField19.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jCheckBox1.setVisible(false);
                jComboBox1.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel15.setVisible(false);
                jLabel18.setVisible(false);
                jLabel22.setVisible(false);
                jButton4.setVisible(false);
                jButton8.setVisible(true);
                jLabel28.setVisible(true);
                jLabel29.setVisible(true);
                jTextField20.setVisible(false);
                jTextField21.setVisible(false);
                jLabel30.setVisible(true);
                jTable2.setVisible(true);
                jTextField22.setVisible(true);
                jTextField23.setVisible(true);
                jTextField24.setVisible(true);
                jCheckBox2.setVisible(true);
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jButton9.setVisible(false);
                jLabel27.setVisible(true);
                jLabel26.setVisible(false);     
                jTextArea1.setRows(0);
                jTextArea1.setRows(0);      
                break;
            case REGISTER:
                jTextField19.setVisible(false);
                jTextField20.setVisible(false);
                jTextField21.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jCheckBox1.setVisible(false);
                jComboBox1.setVisible(false);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel15.setVisible(false);
                jLabel19.setVisible(false);
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jButton9.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jLabel22.setVisible(false);
                break;
            case DOCTOR:
                jTextArea2.setVisible(true);
                jButton10.setVisible(true);  
                jTextArea1.setVisible(true);
                jTable2.setVisible(true);
                jTextField19.setVisible(false);
                jLabel23.setVisible(false);
                jLabel24.setVisible(false);
                jLabel22.setVisible(false);
                jLabel18.setVisible(false);
                jTextField17.setVisible(false);
                jTextField18.setVisible(false);
                jLabel19.setVisible(false);
                jButton4.setVisible(false);
                jCheckBox1.setVisible(false);
                break;
        }

        
        
        jLabel1.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel1.setText("Gender:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel2.setText("Provider: ");

        jLabel3.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel3.setText("Phone Number: ");

        jLabel4.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel4.setText("SSN:");

        jLabel5.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel5.setText("Physician:");

        jLabel6.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel6.setText("Physician Number:");

        jLabel10.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel10.setText("Street Number:");

        jLabel11.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel11.setText("City:");

        jLabel12.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel12.setText("State:");

        jTextField1.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField1.setText(patient.getGender());
        jTextField1.setEditable(false);

        jTextField2.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField2.setText(patient.getProvider());
        jTextField2.setEditable(false);

        jTextField3.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField3.setText(patient.getPhone());
        jTextField3.setEditable(false);

        jTextField4.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField4.setText("" + patient.getSSN());
        jTextField4.setEditable(false);

        jTextField5.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField5.setText(patient.getPhysician());
        jTextField5.setEditable(false);

        jTextField6.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField6.setText(patient.getPhysicianNumber());
        jTextField6.setEditable(false);

        String allergies = "";
        for(String allergy: patient.getAllergies())
        {
            if(allergies.isEmpty())
            {
                allergies = allergy;
            }
            else
            {
                allergies += ", " +allergy;
            }
        }

        jTextField10.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField10.setText(patient.getAddress().getStreet());
        jTextField10.setEditable(false);

        jTextField11.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField11.setText(patient.getAddress().getCity());
        jTextField11.setEditable(false);

        jTextField12.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField12.setText(patient.getAddress().getState());
        jTextField12.setEditable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel15.setText("Symptom:");      

        jLabel31.setFont(new java.awt.Font("宋体", 0, 20)); 
        jLabel31.setText("Discharge Instructions:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        if(user.getUSER_ROLE() == USER_ROLE.DOCTOR)
        {
            jButton10.setText("Set Instructions");
            jTextArea2.setEditable(true);
        }
        else if(user.getUSER_ROLE() == USER_ROLE.NURSE)
        {
            jTextArea2.setEditable(false);
            jTextArea2.setText(patient.getDischargeInstructions());
            jButton10.setText("Print");
        }
        
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {            
                
                if(user.getUSER_ROLE() == USER_ROLE.DOCTOR)
                {
                    db.createDischargeInstructions(patientCollection, patientID, jTextArea2.getText());
                }
                else
                {
                    if(!jTextArea2.getText().equals(""))
                    {
                        Nurse.printDischargeInstructions(patient);
                    }                    
                }

            }
        });


        jLabel16.setText("Diagnosis:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Diagnoses.ABDOMINALPAIN.toString(),
            UHART.Models.Diagnoses.ACUTEUPPERRESPIRATORYINFECTION.toString(),
            UHART.Models.Diagnoses.CHESTPAIN.toString(),
            UHART.Models.Diagnoses.DIZZINESSANDGIDDINESS.toString(),
            UHART.Models.Diagnoses.HEADACHE.toString(),
            UHART.Models.Diagnoses.INJURYOFHEAD.toString(),
            UHART.Models.Diagnoses.LOWERBACKPAIN.toString(),
            UHART.Models.Diagnoses.NONINFECTIVEGASTROENTERITISANDCOLITIS.toString(),
            UHART.Models.Diagnoses.SYNCOPEANDCOLLAPSE.toString(),
            UHART.Models.Diagnoses.URINARYTRACTINFECTION.toString()}));

        jLabel17.setText("Medicines: ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Medications.ACETAMINOPHEN.toString(),
            UHART.Models.Medications.ANTACID.toString(), 
            UHART.Models.Medications.ANTIBIOTIC.toString(),
            UHART.Models.Medications.ANTISEIZURE.toString(),
            UHART.Models.Medications.ASPIRIN.toString(),
            UHART.Models.Medications.FOSCARNET.toString(),
            UHART.Models.Medications.GANCICLOVIR.toString(),
            UHART.Models.Medications.IBUPROFIN.toString(),
            UHART.Models.Medications.SIMETHICONE.toString(),
            UHART.Models.Medications.SUGAR.toString(),
            UHART.Models.Medications.VALGANCICLOVIR.toString()}));

        jLabel19.setText("Nurse info: ");

        jButton4.setText("Add Medical History");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                String medication = jComboBox3.getSelectedItem().toString();
                if(!patient.getMedications().contains(medication))
                {
                    db.createMedications(medication, user, patientID);
                    patient.addMedication(medication);

                    if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ACETAMINOPHEN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ACETAMINOPHEN);
                        db.addBill(UHART.Models.Medications.ACETAMINOPHEN.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTACID.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTACID);
                        db.addBill(UHART.Models.Medications.ANTACID.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTIBIOTIC.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTIBIOTIC);
                        db.addBill(UHART.Models.Medications.ANTIBIOTIC.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ANTISEIZURE.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ANTISEIZURE);
                        db.addBill(UHART.Models.Medications.ANTISEIZURE.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.SUGAR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.SUGAR);
                        db.addBill(UHART.Models.Medications.SUGAR.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.IBUPROFIN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.IBUPROFIN);
                        db.addBill(UHART.Models.Medications.IBUPROFIN.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.SIMETHICONE.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.SIMETHICONE);
                        db.addBill(UHART.Models.Medications.SIMETHICONE.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.GANCICLOVIR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.GANCICLOVIR);
                        db.addBill(UHART.Models.Medications.GANCICLOVIR.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.FOSCARNET.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.FOSCARNET);
                        db.addBill(UHART.Models.Medications.FOSCARNET.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.ASPIRIN.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.ASPIRIN);
                        db.addBill(UHART.Models.Medications.ASPIRIN.getPrice(), patientCollection, patientID);
                    }
                    else if(jComboBox3.getSelectedItem() == UHART.Models.Medications.VALGANCICLOVIR.toString())
                    {
                        patient.getBill().addItem(UHART.Models.Medications.VALGANCICLOVIR);
                        db.addBill(UHART.Models.Medications.VALGANCICLOVIR.getPrice(), patientCollection, patientID);
                    }                    
                    

                    if(jTextField21.getText().isEmpty())
                    {
                        jTextField21.setText(jComboBox3.getSelectedItem().toString());
                    }
                    else
                    {
                        jTextField21.setText(jTextField21.getText() + ", "  +jComboBox3.getSelectedItem().toString());
                    }
                }
                else
                {
                    //TODO: Popup message
                    System.out.println("Medication already added");
                }
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                String diagnosis = jComboBox2.getSelectedItem().toString();
                if(!patient.getDiagnosis().contains(diagnosis))
                {
                                        
                    db.createDiagnosis(diagnosis, user, patientID);
                    patient.addDiagnosis(diagnosis);

                    if(jTextField20.getText().isEmpty())
                    {
                        jTextField20.setText(jComboBox2.getSelectedItem().toString());
                    }
                    else
                    {
                        jTextField20.setText(jTextField20.getText() + ", "  +jComboBox2.getSelectedItem().toString());
                    }
                }
                else
                {
                    //TODO: Popup message
                    System.out.println("Diagnosis already added");
                }
                
                

            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(!jTextArea1.getText().isEmpty())
                {
                    String[] symptomValues = jTextArea1.getText().split(",");    

                    for(int i = 0; i < symptomValues.length; i++)
                    {
                        if(!patient.getSymptoms().get(i).toString().equals(symptomValues[i]))
                        {
                            Symptoms symptom = new Symptoms(symptomValues[i].replaceAll("\\s+", ""));
                            db.createSymptoms(symptom, patientCollection, patientID);
                            patient.setSymptoms(symptom);

                            if(jTextField8.getText().isEmpty())
                            {
                                jTextField8.setText(symptomValues[i].replaceAll("\\s+", ""));
                            }
                            else
                            {
                                jTextField8.setText(jTextField8.getText() + ", " + symptomValues[i].replaceAll("\\s+", ""));
                            }
                        }
                        else
                        {
                            //TODO: Popup button
                            System.out.println(symptomValues[i] + " already added");
                        }                        
                        
                    }

                    jTextArea1.setText("");
                    
                }

            }
        });

        jLabel18.setText("Date:");

        jLabel22.setText("Medication:");

        jTextField17.setText("");

        jTextField18.setText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {                
            },
            new String [] {
                "Date", "Reason"
            }
        ) {
           /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane5.setViewportView(jTable1);

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.REGISTER)
        {
            if(!patient.getMedicalHistory().isEmpty())
            {
                DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
                for(MedicalHistory medHist : patient.getMedicalHistory())
                {
                    model.addRow(new Object[] {medHist.getDate(), medHist.getReason()});
                }
            }            
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nurse", "Date", "Progess"
            }
        ) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable2);

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.REGISTER)
        {           
            if(patient.getProgressReports() != null)
            {
                DefaultTableModel model =(DefaultTableModel) jTable2.getModel();
                for(ProgressReport prog : patient.getProgressReports())
                {
                    model.addRow(new Object[] {prog.getNurseName(), prog.getDate(), prog.getNote()});
                }
            }
            
        }

        jLabel26.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel26.setText("Ordering tests");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { UHART.Models.Tests_procedures.ANGIOGRAM.toString(),
            UHART.Models.Tests_procedures.BLOODTEST.toString(),
            UHART.Models.Tests_procedures.CTSCAN.toString(),
            UHART.Models.Tests_procedures.ECHOCARDIOGRAM.toString(),
            UHART.Models.Tests_procedures.LATERALNECKXRAY.toString(),
            UHART.Models.Tests_procedures.REHABILITATION.toString(),
            UHART.Models.Tests_procedures.STRESSTEST.toString(),
            UHART.Models.Tests_procedures.SURGERY.toString(),
            UHART.Models.Tests_procedures.URINETEST.toString()
        }));

        jLabel7.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel7.setText("Allergies:");

        jLabel8.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel8.setText("Symptoms:");

        jTextField7.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField7.setText(allergies);
        jTextField7.setEditable(false);

        symptoms = "";
        if(patient.getSymptoms() != null)
        {
            for(Symptoms symptom: patient.getSymptoms())
            {
                if(symptoms.isEmpty())
                {
                    symptoms = symptom.toString();
                }
                else
                {
                    symptoms += ", " +symptom.toString();
                }
            }
        }

        jTextField8.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        jTextField8.setText(symptoms);
        jTextField8.setEditable(false);

        medications = "";
        if(patient.getMedications() != null)
        {
            for(String medication: patient.getMedications())
            {
                if(medications.isEmpty())
                {
                    medications = medication.toString();
                }
                else
                {
                    medications += ", " +medication.toString();
                }
            }    
        }
              

        diagnosis = "";
        if(patient.getDiagnosis() != null)
        {
            for(String diagnostic: patient.getDiagnosis())
            {
                if(diagnosis.isEmpty())
                {
                    diagnosis = diagnostic.toString();
                }
                else
                {
                    diagnosis += ", " +diagnostic.toString();
                }
            }   
        }

        jButton5.setText("Add");

        jButton6.setText("Add");

        jTextField21.setText(medications);

        jButton7.setText("Add");

        jLabel28.setText("Nurse");

        jLabel29.setText("Date");

        jLabel30.setText("Progress");

        jTextField22.setText("");

        jTextField23.setText("");

        jTextField24.setText("");

        jButton8.setText("Add Nurse Information");
        jButton8.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Add");
        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(177, 177, 177)
                                            .addComponent(jButton4))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton9)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel31)
                                        .addComponent(jScrollPane4)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel28)))
                                    .addComponent(jLabel19))
                                .addGap(122, 122, 122)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                        .addComponent(jTextField24))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField7, jTextField8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(44, 44, 44)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton5)
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addGap(14, 14, 14)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton6)
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addGap(14, 14, 14)
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton7)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(28, 28, 28))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, jLabel8});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField7, jTextField8});

        jScrollPane2.setViewportView(jPanel2);

        jLabel13.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel13.setText("Zip:");

        jLabel14.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel14.setText("Country:");

        jTextField13.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField13.setText(patient.getAddress().getZipcode());
        jTextField13.setEditable(false);

        jButton1.setText("Back");
        jButton1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                loginManager.showMainPanel(user);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.setVisible(false);
        jButton3.addActionListener(new ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField14.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField14.setText(patient.getAddress().getcountry());
        jTextField14.setEditable(false);

        jTextField15.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField15.setText(patient.getName());
        jTextField15.setEditable(false);

        jLabel20.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel20.setText("Date of Birth:");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel21.setText("Name: ");
        jLabel21.setToolTipText("");

        jTextField16.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jTextField16.setText(patient.getDateOfBirthString());
        jTextField16.setEditable(false);

        jLabel23.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel23.setText("Bill: ");

        jTextField19.setFont(new java.awt.Font("����", 0, 20)); // NOI18N\
        jTextField19.setEditable(false);
        if(user.getUSER_ROLE() == UHART.Models.Staff_Model.USER_ROLE.BILLING)
        {
            if(patient.getBill().getPrice() == 0)
            {
                jTextField19.setText("$0");
                jCheckBox1.setSelected(true);
            }
            else
            {
                jTextField19.setText("$" +patient.getBill().getPrice());
            }
    
        }       

        jCheckBox1.setText("Bill Paid");
        jCheckBox1.setVisible(false);
        
        jButton11.setText("Check out");
        jButton11.setVisible(false);

        try {
            if(patient.getAdmittedBool())
            {
                jCheckBox2.setSelected(true);
            }
        }
        catch(Exception e)
        {
            jCheckBox2.setSelected(false);
        }

        jLabel24.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel24.setText("Bill state");
        jLabel24.setVisible(false);

        jLabel27.setFont(new java.awt.Font("����", 0, 20)); // NOI18N
        jLabel27.setText("Patient Admitted");

        
        if(user.getUSER_ROLE() == USER_ROLE.NURSE && patient.getCheckOut() == false && patient.getAdmittedBool() == true)
        {
            jButton11.setVisible(true);
        }
        jButton11.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                jCheckBox2.setSelected(false);
                db.checkOut(patientCollection, patientID);
                jButton11.setVisible(false);
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(256, 256, 256)
                        .addComponent(jButton3)
                        .addGap(276, 276, 276))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4))
                                    .addComponent(jCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel24)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1076;
        gridBagConstraints.ipady = 823;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
        loginManager.validate();
    }// </editor-fold>//GEN-END:initComponents

    //EDIT
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton3.setVisible(true);
        jButton2.setVisible(false);        

        if(user.getUSER_ROLE() != UHART.Models.Staff_Model.USER_ROLE.BILLING)
        {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
            jTextField19.setEditable(true);
            jTextField10.setEditable(true);
            jTextField11.setEditable(true);
            jTextField12.setEditable(true);
            jTextField13.setEditable(true);
            
            jTextField15.setEditable(true);
            jTextField14.setEditable(true);
            jTextField16.setEditable(true);        
        }
        else
        {
            jCheckBox1.setVisible(true);
            jLabel24.setVisible(true);
        }       
        

    }//GEN-LAST:event_jButton2ActionPerformed

    //SAVE
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
       
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField19.setEditable(false);
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);
        jTextField14.setEditable(false);
        jTextField15.setEditable(false);
        jTextField16.setEditable(false);
        jTextField19.setEditable(false);
        jButton3.setVisible(false);
        jButton2.setVisible(true);

        jCheckBox1.setVisible(false);
        jLabel24.setVisible(false);

        if(jCheckBox1.isSelected())
        {
            //TODO: Implement billing features
            patient.markPaid();
            jTextField19.setText("$" +patient.getBill().getPrice());
            db.markBillPaid(patientID);
        }    
        if(jCheckBox2.isSelected() && patient.getAdmittedBool() == null || jCheckBox2.isSelected() && patient.getAdmittedBool() == false)
        {
            db.admit(patientCollection, patientID);
            if(user.getUSER_ROLE() == USER_ROLE.NURSE)
            {
                jButton11.setVisible(true);
            }
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[] { jTextField17.getText(), jTextField18.getText()});

        MedicalHistory medHistory = new MedicalHistory(jTextField17.getText(), jTextField18.getText());
        
        //System.out.println(patient.getID());

        db.createMedicalHistory(medHistory, patientID);

        jTextField18.setText("");
        jTextField17.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        model.addRow(new Object[] { jTextField22.getText(), jTextField23.getText(), jTextField24.getText()});

        ProgressReport prog = new ProgressReport(jTextField22.getText(), jTextField23.getText(), jTextField24.getText());
        
        //System.out.println(patient.getID());

        db.createProgressReports(prog, user, patientCollection, patientID);

        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String test = jComboBox1.getSelectedItem().toString();
        if(!patient.getTests().contains(test))
        {
            patient.addTests(test);
            if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.ANGIOGRAM.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.ANGIOGRAM, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.ANGIOGRAM.getPrice(), patientCollection, patientID);
            }
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.BLOODTEST.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.BLOODTEST, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.BLOODTEST.getPrice(), patientCollection, patientID);
            }
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.CTSCAN.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.CTSCAN, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.CTSCAN.getPrice(), patientCollection, patientID);
            }        
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.ECHOCARDIOGRAM.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.ECHOCARDIOGRAM, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.ECHOCARDIOGRAM.getPrice(), patientCollection, patientID);
            }        
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.LATERALNECKXRAY.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.LATERALNECKXRAY, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.LATERALNECKXRAY.getPrice(), patientCollection, patientID);
            }        
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.REHABILITATION.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.REHABILITATION, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.REHABILITATION.getPrice(), patientCollection, patientID);
            }
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.STRESSTEST.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.STRESSTEST, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.STRESSTEST.getPrice(), patientCollection, patientID);
            }
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.SURGERY.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.SURGERY, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.SURGERY.getPrice(), patientCollection, patientID);
            }
            else if(jComboBox1.getSelectedItem().toString().equals(UHART.Models.Tests_procedures.URINETEST.toString()))
            {
                db.createTestsProcedures(UHART.Models.Tests_procedures.URINETEST, user, patientCollection, patientID);
                db.addBill(UHART.Models.Tests_procedures.URINETEST.getPrice(), patientCollection, patientID);
            }
        }        

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

   
    

}