/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UHART.Views;

import java.awt.event.ActionListener;

import javax.swing.JTextField;

import UHART.Controllers.LoginManager;
import UHART.Models.Staff_Model;
import java.awt.event.ActionEvent;
import javax.swing.table.TableCellRenderer;
import org.bson.Document;

import UHART.Controllers.AES256;
import UHART.Controllers.JTableButtonModel;
import UHART.Controllers.JTableButtonRenderer;
import UHART.Controllers.JTableMouseListener;
/**
 *
 * @author MSI-PC
 */
public class SearchPatientFrm extends javax.swing.JPanel {

    private JTextField searchField;
    AES256 aes = new AES256();
    /**
     * Creates new form SearchPatientFrm
     */
    public SearchPatientFrm(final LoginManager loginManager, final Staff_Model user) {
        initComponents(loginManager, user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(final LoginManager loginManager, final Staff_Model user) {


        loginManager.setContentPane(this);
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchField = new JTextField();
		searchField.setColumns(10);

        jButton1.setText("Search");
        jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
                            Document search = new Document();
                            if(searchField.getText().isEmpty())
                            {
                                search = null;
                            }
                            else
                            {
                                search.put("ssn", aes.encrypt(searchField.getText()));
                            }
                            
                            TableCellRenderer tableRenderer = new JTableButtonRenderer();
                            JTableButtonModel button = new JTableButtonModel(loginManager, user);
                            button.setRows(search);
                            jTable1.setModel(button);
                            jTable1.getColumn("Patients").setCellRenderer(tableRenderer);
                            //tableRenderer = table.getDefaultRenderer(JButton.class);
                            //table.setDefaultRenderer(JButton.class, new JTableButtonRenderer());
                            jTable1.addMouseListener(new JTableMouseListener(jTable1));
                            
                            //System.out.println(table.getValueAt(0, 0));
                        }
		});	        

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("����", 0, 24)); // NOI18N
        jLabel1.setText("Enter SSN: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)  
                .addGap(20)                         
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE))
            
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jButton1)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()                
                .addGap(50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
